parameters:
    app_path: ''

services:
    controller.resolver:
        class: XI\Core\ControllerResolver
        arguments: [@service_container, %app_path%]

    response.listener:
        class: XI\Core\ResponseListener
        arguments: [%app_path%]

    dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        calls:
            - [addSubscriber, [@response.listener]]

    kernel:
        class: Symfony\Component\HttpKernel\HttpKernel
        arguments: [@dispatcher, @controller.resolver]

    templating.php:
        class: XI\Templating\PHPEngine
        arguments: [{view_path: "%app_path%/view/"}]

    templating.mustache:
        class: XI\Templating\MustacheEngine
        arguments: [{view_path: "%app_path%/view/"}]

    templating:
        alias: templating.mustache