routebase:
    path:     /
    defaults: { _controller: 'ABC\DEF\MyController::base' }

route1:
    path:     /foo
    defaults: { _controller: 'MyController::fooAction' }

route2:
    path:     /foo/bar
    defaults: { _controller: 'MyController::foobarAction' }